.. uml:: 
   
    @startuml diag
      User -> Dashboard: Clicks "Publish"
      activate Dashboard
      Dashboard -> Backend: req saveTale(id)
      activate Backend
      loop each item
        Backend -> Repository: createObject
        Repository --> Backend: objectCreated
      end
      Backend -> Repository: req createPackage
      Repository --> Backend: resp packageCreated
      Backend --> Dashboard: resp taleSaved(id)
      deactivate Backend
      Dashboard --> User: Updates UI
      deactivate Dashboard
    @enduml
